config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site/home#index'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: %i[edit create]
    resources :categories, except: %i[show destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: %i[index edit update new create]
      resources :my_data, only: %i[edit update]
    end
    resources :ad_detail, only: %i[index show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, skip: [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
end

app/controllers/backoffice/admins_controller.rb
# frozen_string_literal: true

module Backoffice
  class AdminsController < BackofficeController
    before_action :set_admin, only: %w[edit update destroy]
    after_action :verify_authorized, only: %w[new destroy]
    after_action :verify_policy_scoped, only: :index

    def index
      @admins = policy_scope(Admin)
    end

    def new
      @admin = Admin.new
      authorize @admin
    end

    def create
      @admin = Admin.new(params_admin)
      if @admin.save
        redirect_to backoffice_admins_path,
                    notice: "O Administrador (#{@admin.email}) foi cadastrado com sucesso."
      else
        render :new
      end
    end

    def edit; end

    def update
      if @admin.update(params_admin)
        AdminMailer.update_email(current_admin, @admin).deliver_now
        redirect_to backoffice_admins_path,
                    notice: "O Administrador (#{@admin.email}) foi atualizado com sucesso."
      else
        render :edit
      end
    end

    def destroy
      authorize @admin

      if @admin.destroy
        redirect_to backoffice_admins_path,
                    notice: "O Administrador (#{@admin.email}) foi excluído com sucesso."
      else
        render :index
      end
    end

    private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      params[:admin].except!(:password, :password_confirmation) if password_blank?

      if @admin.blank?
        params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
      else
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

    def password_blank?
      params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
    end
  end
end

app/controllers/backoffice/categories_controller.rb
# frozen_string_literal: true

module Backoffice
  class CategoriesController < BackofficeController
    before_action :set_category, only: %w[edit update]

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = CategoryService.create(paramas_category)
      if @category.save
        redirect_to backoffice_categories_path,
                    notice: "A categoria (#{@category.description}) foi cadastrada com sucesso."
      else
        render :new
      end
    end

    def edit; end

    def update
      if @category.update(paramas_category)
        redirect_to backoffice_categories_path,
                    notice: "A categoria (#{@category.description}) foi atualizada com sucesso."
      else
        render :edit
      end
    end

    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def paramas_category
      params.require(:category).permit(:description)
    end
  end
end

app/controllers/backoffice/categories_controller/category_service.rb
# frozen_string_literal: true

module Backoffice
  class CategoriesController::CategoryService
    attr_accessor :category

    def self.create(params_category)
      @category = Category.new(params_category)
      @category.save! if @category.valid?
      @category
    end
  end
end

app/controllers/backoffice/dashboard_controller.rb
# frozen_string_literal: true

module Backoffice
  class DashboardController < BackofficeController
    def index; end
  end
end

app/controllers/backoffice/diagrams_controller.rb
# frozen_string_literal: true

module Backoffice
  class DiagramsController < BackofficeController
    def index
      `bundle exec erd --filename='public/diagram'`
    end
  end
end

app/controllers/backoffice/send_mail_controller.rb
# frozen_string_literal: true

module Backoffice
  class SendMailController < ApplicationController
    def edit
      @admin = Admin.find(params[:id])
      respond_to do |format|
        format.js
      end
    end

    def create
      begin
        send_admin_message
      rescue StandardError
        @notify_message = 'Erro ao enviar email. Tente novamente'
        @notify_flag = 'error'
      end
      respond_to do |format|
        format.js
      end
    end

    def send_admin_message
      AdminMailer.send_message(current_admin,
                               params[:'recipient-text'],
                               params[:subject_text],
                               params[:'message-text']).deliver_now

      @notify_message = 'Email enviado com sucesso!'
      @notify_flag = 'success'
    end
  end
end

app/controllers/backoffice_controller.rb
# frozen_string_literal: true

class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'backoffice'

  def pundit_user
    current_admin # current_user to Pundit
  end
end

app/helpers/backoffice/admins_helper.rb
# frozen_string_literal: true

module Backoffice
  module AdminsHelper
    OptionsForRoles = Struct.new(:id, :description)

    def options_for_roles
      Admin.roles_i18n.map do |key, value|
        OptionsForRoles.new(key, value)
      end
    end
  end
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: { action: 'Editando Administrador'} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= @admins.model_name.human(count: 2) %></h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('messages.listing', model: @admins.model_name.human(count: 2)) %>
    <% if policy(@admins).new? %>
      <%= link_to new_backoffice_admin_path,
          class:"btn btn-success btn-circle pull-right", style:"margin-top: -7px" do %>
            <i class="fa fa-plus"></i>
          <% end %>
    <% end %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th><%= @admins.model.human_attribute_name('name') %></th>
            <th><%= @admins.model.human_attribute_name('role') %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.id %></td>
              <td><%= admin.name %></td>
              <td><%= admin.role_i18n %></td>
              <td style="width: 150px">
                <%= link_to edit_backoffice_send_mail_path(admin) , class: "btn btn-info btn-circle", remote: true do %>
                  <i class="fa fa-envelope"></i>
                <% end %>
                <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <% if (current_admin.id != admin.id) && policy(@admins).destroy? %>
                  <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle",
                      data: {confirm: t('messages.confirm_with', item: admin.name )} do %>
                        <i class="fa fa-minus"></i>
                      <% end %>
                <% else %>
                  <%= link_to '#', disabled: "disabled", class: "btn btn-danger btn-circle" do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <!-- /.table-responsive -->
  </div>
<!-- /.panel-body -->
</div>

<%= render partial: 'backoffice/admins/shared/send_mail_modal' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: { action: 'Novo Administrador' } %>