config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site/home#index'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: %i[edit create]
    resources :categories, except: %i[show destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: %i[index edit update new create]
      resources :my_data, only: %i[edit update]
    end
    resources :ad_detail, only: %i[index show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, skip: [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>

<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for([:backoffice, @admin]) do |f| %>
        <div class="form-group">
          <label>Nome</label>
          <%= f.text_field :name, class:"form-control", placeholder:"Nome do administrador" %>
        </div>
        <% if policy(@admin).edit? %>
          <div class="form-group">
            <%= f.label :role %>
            <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
              <div class="radio">
                <%= b.label { b.radio_button + b.text} %>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <label>Email</label>
          <%= f.text_field :email, class:"form-control", placeholder:"Email do administrador" %>
        </div>

        <div class="form-group">
          <label>Senha</label>
          <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>
        </div>

        <div class="form-group">
          <label>Confirmação de Senha</label>
          <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de Senha" %>
        </div>

        <button type="submit" class="btn btn-default">Salvar </button>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-text" class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, class: "form-control", required: "required") %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
          <%= submit_tag t('buttons.send_message'), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>