config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'site/home#index'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: %i[edit create]
    resources :categories, except: %i[show destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: %i[index edit update new create]
      resources :my_data, only: %i[edit update]
    end
    resources :ad_detail, only: %i[index show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, skip: [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  # RatyRate gem
  ratyrate_rater

  # Associations
  has_many :ads, dependent: :destroy
  has_one :profile_member, dependent: :destroy
  accepts_nested_attributes_for :profile_member

  # Validation
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nested_attributes
    return unless nested_attributes_blank?

    message = 'É necessário preencer os campos Primeiro e Segundo nome.'
    errors.add(:base, message)
  end

  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.second_name.blank?
  end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

module Members
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    def new
      build_resource({})
      resource.build_profile_member
      respond_with resource
    end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(
        :sign_up,
        keys:
          [ 
            :email, :password, :password_confirmation,
            profile_member_attributes: %i[first_name second_name]
          ]
      )
    end
  end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

module Members
  class SessionsController < Devise::SessionsController
    def new
      super do |resource|
        resource.build_profile_member
      end
    end

    protected

    def after_sign_in_path_for(resource)
      stored_location = stored_location_for(resource)
      if stored_location.match(site_ad_detail_index_path)
        stored_location
      else
        site_profile_dashboard_index_path
      end
    end
  end
end

app/views/members/shared/_form.html.erb
<div class="container">
  <div id="loginbox" style="<%= devise_sign_in? %> margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="panel-title">Sign In</div>
        <div style="float:right; font-size: 80%; position: relative; top:-18px">
          <%= link_to t('labels.forgot_password'), new_member_password_path %>
        </div>
      </div>
      <div style="padding-top:30px" class="panel-body">
        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name),
        html: { class: "form-horizontal", role:"form" }) do |f| %>
          <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= f.email_field :email, autofocus: true, class:"form-control", placeholder:"Email" %>
          </div>
          <div style="margin-bottom: 25px" class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"Senha" %>
          </div>
          <div class="input-group">
            <div class="checkbox">
              <label>
                <% if devise_mapping.rememberable? -%>
                  <%= f.check_box :remember_me %>
                  Lembrar-me
                <% end -%>
              </label>
            </div>
          </div>

          <div style="margin-top:10px" class="form-group">
            <!-- Button -->
            <div class="col-sm-12 controls">
              <%= f.submit "Entrar", class:"btn btn-success" %>
              <a id="btn-fblogin" href="#" class="btn btn-primary" disabled="disabled">Login with Facebook</a>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12 control">
              <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                Don't have an account!
                <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                  Sign Up Here
                </a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="signupbox" style="<%= devise_sign_up? %> margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="panel-title">Sign Up</div>
      <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
    </div>
    <div class="panel-body" >
      <%= form_for(resource, as: resource_name, url:
          registration_path(resource_name), html: { class: "form-horizontal", role:"form" }) do |f| %>
        <div class="form-group">
          <%= f.label :email, class:"col-md-3 control-label" %>
          <div class="col-md-9">
            <%= f.email_field :email, autofocus: true, class:"form-control", placeholder:"Email Address" %>
          </div>
        </div>
        <%= f.fields_for :profile_member do |profile_fields| %>
          <div class="form-group">
            <%= profile_fields.label :first_name, class:"col-md-3 control-label" %>
            <div class="col-md-9">
              <%= profile_fields.text_field :first_name, class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= profile_fields.label :second_name, class:"col-md-3 control-label" %>
            <div class="col-md-9">
              <%= profile_fields.text_field :second_name, class:"form-control" %>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :password, class:"col-md-3 control-label" %>
          <div class="col-md-9">
            <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder:"Password" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class:"col-md-3 control-label" %>
          <div class="col-md-9">
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder:"Password Confirmation" %>
          </div>
        </div>
        <div class="form-group">
          <!-- Button -->
          <div class="col-md-offset-3 col-md-9">
            <%= f.submit "Sign up", class:"btn btn-info" do %>
              <i class="icon-hand-right"></i>&nbsp Sign Up
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% flash.each do |key, value| %>
      <%= javascript_tag "$.notify( { message: '#{value}'}, { type: 'danger',
      placement: { from: 'top', align: 'center' }});" %>
<% end %>

<% unless 'devise/shared/error_message'
.blank? %>
  <% resource.errors.full_messages.each do |message| %>
    <%= javascript_tag "$.notify( { message: '#{message}'}, { type: 'danger',
      placement: { from: 'top', align: 'center' }});" %>
  <% end %>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>